In [1]:
#1. Импорт библиотеки NumPy с общепринятым сокращением
import numpy as np



In [2]:
#2. Примеры создания массивов

#2.1. Из обычных списков

arr1 = np.array([1, 2, 3, 4, 5])
arr1

array([1, 2, 3, 4, 5])

In [11]:
#2.2. Массив из двумерного списка

arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
#2.3. Массив с использованием функций `zeros`

zeros = np.zeros((3, 4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
#2.4. Массив с использованием функций `ones`

ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
#3. Демонстрация атрибутов
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr.shape)
print(arr.dtype)

(3, 4)
int64


In [15]:
#4. Примеры индексирования и срезов:

arr_4 = np.arange(1, 90, 5)
print("2-ый элемент массива:", arr_4[1])
print("Срез:",arr_4[3::3]) #Срез с 3 элемента с шагом 3 


2-ый элемент массива: 6
Срез: [16 31 46 61 76]


In [16]:
#5. Примеры векторных операций и базовых статистик:

a = np.array([1, 2, 3, 4, 5, 6])
b = np.array([10, 11, 12, 13, 14 ,15])

print(a + b)
print(b - a)
print(np.mean(a))

[11 13 15 17 19 21]
[9 9 9 9 9 9]
3.5
